### ISSUE TITLE
Udemy courses links are pointing to wrong url

### ISSUE THREAD

**Issue by Seralto** [gophertuts/go-basics#1]
## Description
All Udemy courses in https://github.com/gophertuts/go-basics/tree/master/go-learning-resources are pointing to wrong url:
https://github.com/golang/go/wiki/Books

## The correct urls are:

```md
- [Learn How To Code: Google's Go (golang) Programming Language - T. McCleod](https://www.udemy.com/course/learn-how-to-code/)
- [Web Development w/ Google’s Go (golang) Programming Language - T. McCleod](https://www.udemy.com/course/go-programming-language/)
- [Go: The Complete Developer's Guide (Golang) - Stephen Grider](https://www.udemy.com/course/go-the-complete-developers-guide/)
```

**Comment by steevehook** [comment]
> ## Description
> All Udemy courses in https://github.com/gophertuts/go-basics/tree/master/go-learning-resources are pointing to wrong url:
> https://github.com/golang/go/wiki/Books
> 
> ## The correct urls are:
> ```lisp
> - [Learn How To Code: Google's Go (golang) Programming Language - T. McCleod](https://www.udemy.com/course/learn-how-to-code/)
> - [Web Development w/ Google’s Go (golang) Programming Language - T. McCleod](https://www.udemy.com/course/go-programming-language/)
> - [Go: The Complete Developer's Guide (Golang) - Stephen Grider](https://www.udemy.com/course/go-the-complete-developers-guide/)
> ```

Good catch @Seralto guess I was copy pasting things around and forgot to change this one

**Comment by Seralto** [comment]
Blessed/damned `CTRL+C` `CTRL+V` :)
